server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mariadb}

springdoc:
  swagger-ui:
    path: /swagger
    enabled: ${SWAGGER_UI_ENABLED:true}
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: WARN
    org.springframework: INFO
    com.company: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: logs/application.log
#    max-size: 10MB
#    max-history: 5